task: named-entity-recognition

dataset:
  data_file:
    train: 'train.json'
    valid: 'train.json'
  data_type: json-tags

preprocessor:
  type: sequence-labeling-preprocessor
  max_length: 150

data_collator: SequenceLabelingDataCollatorWithPadding

model:
  type: sequence-labeling-model
  embedder:
    model_name_or_path: google-bert/bert-base-cased
  dropout: 0.1
  use_crf: true

train:
  max_epochs: 20
  dataloader:
    batch_size_per_gpu: 16
  optimizer:
    type: AdamW
    lr: 5.e-5
    param_groups:
      - regex: crf
        lr: 5.e-1
  lr_scheduler:
    type: LinearLR
    start_factor: 1.0
    end_factor: 0.0
    total_iters: 20

evaluation:
  dataloader:
    batch_size_per_gpu: 128
  metrics:
    - type: ner-metric
    - type: ner-dumper
      model_type: sequence_labeling
      dump_format: json-tags
